### ISSUE TITLE
PDF document not rendering at the top of the page

### ISSUE THREAD

**Issue by cerdts** [uppercuut/TemplateToPdf.Demo#1]
When the HTML template is rendered into a PDF the top of the content appears several inches down from the top of the PDF document.  I verified this by setting the HTML Body background-color to gray.  I noticed the same thing is happening when using the Umbraco Starter Kit as shown in your Getting Started document.

**Comment by IbrahimMNada** [comment]
Hello, 
thank you for issuing the very first bug!! 

The issue has been fixed in 1.8  

the `PdfUrlBuilder` now has a new method you can set the page margins 

`WithMargins(int topMargin = 0, int bottomMargin = 0, int leftMargin = 0, int rightMargin = 0)`

final usage sample : 

`var pdfUrl = new PdfUrlBuilder().UsingGetByIdMethod(person.Id).WithTemplateAlias("ResumeTemplate").AddPdfFileName(person.Name).WithMargins(4,4,4,4).Url();`

its defaulted to zero 
![image](https://user-images.githubusercontent.com/28313687/161624437-dcffeee4-f076-4682-93f7-cd7bf224b082.png)
